apiVersion: apps/v1
kind: Deployment
metadata:
  name: foodui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foodui
  template:
    metadata:
      labels:
        app: foodui                 
    spec:
      containers:
      - name: foodui
        image: arambazamba/foodui
        imagePullPolicy: Always
        ports:
        - containerPort: 80        
        resources:
          limits:            
            cpu: "500m"
            memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: foodui
spec:
  type: LoadBalancer
  ports:
  - port: 8081
    targetPort: 80
  selector:
    app: foodui
---
